services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: pgsql
    ports:
      - "5432:5432"
    volumes:
      - /home/ilham/dev/docker/pgsql:/var/lib/postgresql/data
